name: Silta
recipe: drupal8

config:
  webroot: web
  via: nginx
  php: '7.2'
  database: mariadb:10.2
  #xdebug: true

tooling:
  codeception:
    service: appserver
    description: Run codeception
    cmd:
      - ./vendor/bin/codecept
      - "--env=lando"
  npm:
    description: Runs npm commands
    service: node

services:
  appserver:
    build:
      - composer install
    overrides:
      environment:
        HASH_SALT: notsosecurehash
  # chrome:
  #   type: compose
  #   services:
  #     image: selenium/standalone-chrome
  #     user: root
  #     ports:
  #       - "4444:4444"
  #     volumes:
  #       - /dev/shm:/dev/shm
  #     command: /opt/bin/entry_point.sh
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: node
    build:
      - npm install

proxy:
  mailhog:
    - mail.lndo.site

events:
  # Clear caches after a database import
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y

