name: Silta
recipe: drupal8

compose:
  - compose.yml

config:
  webroot: web
  via: nginx
  php: '7.1'
  database: mariadb:10.1
  #xdebug: true

tooling:
  codeception:
    service: appserver
    description: Run codeception
    cmd:
      - ./vendor/bin/codecept
      - "--env=lando"

services:  
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

  appserver:
    overrides:
      services:
        environment:
          HASH_SALT: notsosecurehash

proxy:
  mailhog:
    - mail.lndo.site

events:
  # Clear caches after a database import
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y

