name: Silta
recipe: drupal8

config:
  webroot: web
  via: nginx
  php: '7.2'
  database: mariadb:10.2
  #xdebug: true

tooling:
  codeception:
    service: appserver
    description: Run codeception
    cmd:
      - ./vendor/bin/codecept
      - "--env=lando"
  npm:
    description: Runs npm commands
    service: node

services:
  appserver:
    overrides:
      environment:
        HASH_SALT: notsosecurehash
  # chrome:
  #   type: compose
  #   services:
  #     image: selenium/standalone-chrome
  #     user: root
  #     ports:
  #       - "4444:4444"
  #     volumes:
  #       - /dev/shm:/dev/shm
  #     command: /opt/bin/entry_point.sh
  elasticsearch:
    services:
      # CORS settings.
      command: docker-entrypoint.sh elasticsearch -Ecluster.name=catalog -Ehttp.port=9200 -Ehttp.cors.allow-origin="*" -Ehttp.cors.enabled=true -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization -Ehttp.cors.allow-credentials=true
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.1
      ports:
        - "9200"
        - "9300"
    type: compose
  kibana:
    services:
      command: ./bin/kibana
      depends_on:
        - elasticsearch
      image: docker.elastic.co/kibana/kibana-oss:6.8.1
      ports:
        - "5601"
    type: compose   
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: node
    build:
      - npm install

proxy:
  elasticsearch:
    - es.lndo.site:9200
  kibana:
    - kibana.lndo.site:5601
  mailhog:
    - mail.lndo.site

events:
  pre-start:
    - appserver: composer install
  # Clear caches after a database import
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y
