name: Silta
recipe: drupal8

config:
  webroot: web
  via: nginx
  php: '7.2'
  database: mariadb:10.2

tooling:
  codeception:
    service: appserver
    description: Runs Codeception tests
    cmd: /app/vendor/bin/codecept
  drush:
    description: Runs Drush version defined in Composer
    cmd: /app/vendor/bin/drush --root=/app/web
  npm:
    description: Runs npm commands
    service: node
  phpcs:
    service: appserver
    description: Runs PHP_CodeSniffer
    cmd: /app/vendor/bin/phpcs
  phpcbf:
    service: appserver
    description: Runs PHP Code Beautifier and Fixer
    cmd: /app/vendor/bin/phpcbf
  phpstan:
    service: appserver
    description: Runs PHP Static Analysis Tool
    cmd: /app/vendor/bin/phpstan
  phpunit:
    service: appserver
    description: Runs PHPUnit tests
    cmd: /app/vendor/bin/phpunit
  yarn:
    description: Runs Yarn commands
    service: node

services:
  appserver:
    run:
      - cd /app && composer install
    overrides:
        environment:
          HASH_SALT: notsosecurehash
  chrome:
    type: compose
    services:
      image: selenium/standalone-chrome
      user: root
      ports:
        - "4444:4444"
      volumes: 
        - /dev/shm:/dev/shm
      command: /opt/bin/entry_point.sh
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: node:10
    build:
      - yarn

proxy:
  mailhog:
    - mail.lndo.site

events:
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y
