#ddev-generated
services:
  kibana:
    build:
      context: ./kibana
      dockerfile: Dockerfile
      args:
        - KIBANA_VERSION=8.10.2
    environment:
      KIBANA_VERSION: 8.10.2
      ELASTICSEARCH_HOSTS: '["http://ddev-${DDEV_SITENAME}-elasticsearch:9200"]'
      VIRTUAL_HOST: $DDEV_HOSTNAME
      HTTP_EXPOSE: 5600:5601
      HTTPS_EXPOSE: 5601:5601