name: 'Wunderful theme & Theming Tools'
description: 'Installs and configures the most communly used modules for front-end development'
type: 'Site'
install:
  - twig_tweak
  - twig_field_value
# config:
  # strict: false
  # actions: