#ddev-generated
hooks:
  pre-start:
    # Install or update the wunderio/ddev-wunderio-drupal add-on if needed.
    # Developers don't need to do this manually. They just need to clone the
    # project and run ddev start.
    # We check for wdr-core.sh existence (introduced in 0.5.0) to detect if
    # the add-on is missing or a pre-0.5.0 version is installed. Versions 0.5.0
    # and later are checked for updates by host-post-start-update-check.sh.
    - exec-host: 'if [ ! -f "${DDEV_GLOBAL_DIR}/wunderio/core/wdr-core.sh" ]; then ddev add-on get wunderio/ddev-wunderio-drupal; fi'
  post-start:
    # Build hook workaround to run composer install on first start.
    # @todo We could potentially make this work from recognizing the command.
    - exec: |
        if ! command -v wdr-core &> /dev/null; then
          ln -s /mnt/ddev-global-cache/wunderio/core/wdr-core.sh /usr/local/bin/wdr-core
        fi
        # Run once start hook if needed
        if [ ! -f "/mnt/wdr-hooks/ddev_web_post_start_once" ]; then
          /usr/local/bin/wdr-core hooks web-post-start-once.sh;
          sudo touch /mnt/wdr-hooks/ddev_web_post_start_once
        fi
    # Script to run on every start on the host.
    - exec-host: '${DDEV_GLOBAL_DIR}/wunderio/core/wdr-core.sh hooks host-post-start.sh'
    # Script to run on every start.
    - exec: "wdr-core hooks web-post-start.sh"
    # Update check.
    - exec-host: '${DDEV_GLOBAL_DIR}/wunderio/core/wdr-core.sh hooks host-post-start-update-check.sh'
  post-import-db:
    - exec: "wdr-core hooks db-post-import.sh"
  post-restore-snapshot:
    - exec: "wdr-core hooks db-post-import.sh"
# When Mutagen is enabled (which it is by default in DDEV v1.19+),
# these directories are bind-mounted directly rather than synced via Mutagen
# This improves performance for large file directories by bypassing Mutagen's
# syncing.
# The paths are relative to the project root.
upload_dirs:
  # Configure database_dumps directory to be bind-mounted directly
  # instead of being synced via Mutagen for better performance
  - ../database_dumps
