#ddev-generated
services:
  adminer:
    container_name: ddev-${DDEV_SITENAME}-adminer
    build:
      context: './adminer'
    environment:
      # Use the line below to change the adminer theme.
      # - ADMINER_DESIGN=nette
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_PLUGINS=tables-filter
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=9100:8080
      - HTTPS_EXPOSE=9101:8080
      - DDEV_DBIMAGE
      - DDEV_DB_NAME=db
      - DDEV_DB_USER=db
      - DDEV_DB_PASS=db
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
    - ".:/mnt/ddev_config"
    - "ddev-global-cache:/mnt/ddev-global-cache"
    depends_on:
    - db

  web:
    links:
      - adminer:adminer
